name: Reusable Terraform CD

on:
  workflow_call:
    inputs:
      terraform-version:
        description: Terraform version to use
        required: true
        type: string

      working-directory:
        description: Terraform working directory
        required: false
        type: string
        default: .

      deployment:
        description: Whether Terraform changes should be applied
        required: true
        type: boolean

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}

    steps:
      - name: Checkout consumer repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ inputs.terraform-version }}

      - name: Terraform version
        run: terraform version

      - name: Terraform init
        run: terraform init

      - name: Terraform plan
        run: terraform plan

      - name: Terraform apply
        if: inputs.deployment
        run: terraform apply -auto-approve
